version: 1
job:
  description: "this job parse nginx logs using grok expression and stored into nginx table"
  tags:
  - "demo"
  - "nginx"
  - "grok"
  type: "ingestion"
source:
  endpoint: "lo_lfs"
  properties:
    format: "text"
    format_properties:
      parser:
        type: "grok"
        pattern: "%{IPORHOST:clientip} (?:-|%{USER:ident}) (?:-|%{USER:auth}) \\\\[%{HTTPDATE:timestamp}\\\\] \\\\\"(?:%{WORD:verb} %{NOTSPACE:request}(?: HTTP/%{NUMBER:httpversion})?|-)\\\\\" %{NUMBER:response} (?:-|%{NUMBER:bytes})"
    source_file_pattern: "grok/access.log*"
    charset: "UTF-8"
    partial_load: true
schema:
  strict_schema_check: true
  schema_derivation_strategy: "source"
  discard: true
target:
  endpoint: "lo_lfs"
  properties:
    format: "delimited"
    charset: "UTF-8"
    format_properties:
      column_delimiter: ","
      quote_delimiter: "\""
      merge_file: true
      contains_header: true
    path: "grok-target"
