folder: "af1/af2"
job:
  type: "ingestion"
  tags:
  - "demo"
  - "nginx"
  - "grok"
  description: "this job parse nginx logs using grok expression and stored into nginx table"
schema:
  schema_derivation_strategy: "source"
  strict_schema_check: true
  discard: true
source:
  endpoint: "lo_lfs"
  properties:
    source_file_pattern: "grok/access.log*."
    format: "text"
    charset: "UTF-8"
    partial_load: true
    format_properties:
      clean_column_name: false
      parser:
        pattern: "%{IPORHOST:clientip} (?:-|%{USER:ident}) (?:-|%{USER:auth}) \\\\[%{HTTPDATE:timestamp}\\\\] \\\\\"(?:%{WORD:verb} %{NOTSPACE:request}(?: HTTP/%{NUMBER:httpversion})?|-)\\\\\" %{NUMBER:response} (?:-|%{NUMBER:bytes})"
        type: "grok"
target:
  endpoint: "lo_lfs"
  properties:
    format: "delimited"
    charset: "UTF-8"
    path: "grok-target"
    format_properties:
      column_delimiter: ","
      quote_delimiter: "\""
      contains_header: true
      merge_file: true
version: 1
